<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'ECiu',
  'author' => 'Leiver Espinoza',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'GProConneXt',
  'published_date' => '2016-10-25 05:46:52',
  'type' => 'module',
  'version' => 1477374412,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'GProConneXt',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'ECiu_resources',
      'class' => 'ECiu_resources',
      'path' => 'modules/ECiu_resources/ECiu_resources.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'ECiu_resource_types',
      'class' => 'ECiu_resource_types',
      'path' => 'modules/ECiu_resource_types/ECiu_resource_types.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'ECiu_sgt',
      'class' => 'ECiu_sgt',
      'path' => 'modules/ECiu_sgt/ECiu_sgt.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'ECiu_badges',
      'class' => 'ECiu_badges',
      'path' => 'modules/ECiu_badges/ECiu_badges.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'ECiu_ddc',
      'class' => 'ECiu_ddc',
      'path' => 'modules/ECiu_ddc/ECiu_ddc.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'ECiu_denominations',
      'class' => 'ECiu_denominations',
      'path' => 'modules/ECiu_denominations/ECiu_denominations.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'ECiu_languages',
      'class' => 'ECiu_languages',
      'path' => 'modules/ECiu_languages/ECiu_languages.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'ECiu_tracks',
      'class' => 'ECiu_tracks',
      'path' => 'modules/ECiu_tracks/ECiu_tracks.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_resources',
      'to' => 'modules/ECiu_resources',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_resource_types',
      'to' => 'modules/ECiu_resource_types',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_sgt',
      'to' => 'modules/ECiu_sgt',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_badges',
      'to' => 'modules/ECiu_badges',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_ddc',
      'to' => 'modules/ECiu_ddc',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_denominations',
      'to' => 'modules/ECiu_denominations',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_languages',
      'to' => 'modules/ECiu_languages',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ECiu_tracks',
      'to' => 'modules/ECiu_tracks',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);